name: Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install standard
        run: npm install --save-dev standard-version

      - name: Commit and push changes
        run: |
          git config --local user.email "felipe.goulart1999@gmail.com"
          git config --local user.name "felipebgoulart"
          git add -A
          git commit -m "chore(release): generate changelog and version"
          git push

      - name: Generate Changelog
        run: npx standard-version

      - name: Commit and push changes
        run: |
          git config --local user.email "felipe.goulart1999@gmail.com"
          git config --local user.name "felipebgoulart"
          git add -A
          git commit -m "chore(release): generate changelog and version"
          git push
